[functions]
  directory = "./functions"

[[redirects]]
  from = "/*"
  to = "index.html"
  status = 200

[[redirects]]
  from = "index.html"
  to = "/.netlify/functions/og-tags/:splat"
  status = 200
